let speaking = false;
let currentAudio: HTMLAudioElement | null = null;

export function isBembaSpeaking(): boolean {
  return speaking;
}

/**
 * BembaTranslate Offline TTS
 *
 * Integration point for the local Bemba voice model:
 *
 * model.onnx
 * config.json
 * tokenizer_config.json
 * vocab.json
 *
 * Target audio:
 * 22050 Hz
 * Mono
 * Float32 PCM
 *
 * No internet connection or cloud speech service is used.
 */

export async function speakBemba(text: string): Promise<void> {
  const value = text.trim();

  if (!value || speaking) {
    return;
  }

  speaking = true;

  try {
    /*
     * The real ONNX model is intentionally kept separate
     * from the UI.
     *
     * The model must first be loaded and its exact ONNX
     * input/output contract detected before inference.
     *
     * This prevents us from sending the wrong tensor to
     * model.onnx and producing broken audio.
     */

    console.log("[Bemba TTS] Requested:", value);

    await new Promise<void>((resolve) => {
      window.setTimeout(resolve, 100);
    });
  } catch (error) {
    console.error("[Bemba TTS] Error:", error);
  } finally {
    speaking = false;
  }
}

/**
 * Stop currently playing Bemba speech.
 */
export function stopBembaSpeech(): void {
  if (currentAudio) {
    currentAudio.pause();
    currentAudio.currentTime = 0;
    currentAudio.src = "";
    currentAudio = null;
  }

  speaking = false;
}

/**
 * Prepare Float32 PCM audio for browser playback.
 *
 * The Bemba model produces:
 * 22050 Hz
 * mono
 * Float32 PCM
 */
export function createBembaWav(
  samples: Float32Array,
  sampleRate = 22050
): Blob {
  const buffer = new ArrayBuffer(44 + samples.length * 2);
  const view = new DataView(buffer);

  const writeString = (offset: number, value: string) => {
    for (let i = 0; i < value.length; i++) {
      view.setUint8(offset + i, value.charCodeAt(i));
    }
  };

  writeString(0, "RIFF");
  view.setUint32(4, 36 + samples.length * 2, true);
  writeString(8, "WAVE");

  writeString(12, "fmt ");
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true); // PCM
  view.setUint16(22, 1, true); // Mono
  view.setUint32(24, sampleRate, true);

  const byteRate = sampleRate * 2;
  view.setUint32(28, byteRate, true);

  view.setUint16(32, 2, true);
  view.setUint16(34, 16, true);

  writeString(36, "data");
  view.setUint32(40, samples.length * 2, true);

  let offset = 44;

  for (let i = 0; i < samples.length; i++) {
    const sample = Math.max(-1, Math.min(1, samples[i]));

    const pcm =
      sample < 0
        ? sample * 0x8000
        : sample * 0x7fff;

    view.setInt16(offset, pcm, true);
    offset += 2;
  }

  return new Blob([buffer], {
    type: "audio/wav",
  });
}

/**
 * Play Float32 PCM generated by the Bemba ONNX model.
 */
export async function playBembaPcm(
  samples: Float32Array,
  sampleRate = 22050
): Promise<void> {
  stopBembaSpeech();

  const wav = createBembaWav(samples, sampleRate);
  const url = URL.createObjectURL(wav);

  const audio = new Audio(url);

  currentAudio = audio;
  speaking = true;

  try {
    await audio.play();

    await new Promise<void>((resolve) => {
      audio.onended = () => resolve();
      audio.onerror = () => resolve();
    });
  } finally {
    audio.pause();
    audio.src = "";

    URL.revokeObjectURL(url);

    if (currentAudio === audio) {
      currentAudio = null;
    }

    speaking = false;
  }
}
